# -*- coding: utf-8 -*-
"""DMDW Lab 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zzib_igsZUpYI42PXM7kIoD-O7POSSc
"""

import pandas as pd
url="https://raw.githubusercontent.com/Anasuya-Sahoo/DMDW-Lab/main/student-mat.csv"
df=pd.read_csv(url,sep=',')
df.head()

"""Proximity Measures for binary attributes"""

import numpy as np
import seaborn as sbs
import matplotlib.pyplot as plt

dfs=df[['schoolsup','famsup','paid','activities','nursery','higher','internet','romantic']]
dfs.head()

dfs=dfs.replace('yes',1)
dfs=dfs.replace('no',0)

dfs.head()

n=np.array(dfs[['schoolsup','famsup']])
n=n.reshape(-1,2)
n.shape

m=np.array(dfs[['internet','romantic']])
m=n.reshape(-1,2)
m.shape

from scipy.spatial import distance

dist_matrix=distance.cdist(n,m)
print(dist_matrix)

dist_matrix.shape

sbs.heatmap(dist_matrix)
plt.show()

"""Proximity Measures for numeric attribute"""

numeric=df[['age','Medu','Fedu','traveltime','studytime','failures']]
numeric.head()

num1=np.array(numeric[['age','failures']])
num1.reshape(-1,2)
num1.shape

num2=np.array(numeric[['Medu','Fedu']])
num2.reshape(-1,2)
num2.shape

dist_matrix=distance.cdist(num1,num2)
print(dist_matrix)

sbs.heatmap(dist_matrix)
plt.show()